// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-pJfFVndCqQENAsYHNjd9-kLVwz-wXsw',
    appId: '1:1066615778167:web:eb326011ac316be1a18f72',
    messagingSenderId: '1066615778167',
    projectId: 'farm-to-home-8c520',
    authDomain: 'farm-to-home-8c520.firebaseapp.com',
    storageBucket: 'farm-to-home-8c520.firebasestorage.app',
    measurementId: 'G-H9GD71QDLP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApSbb_ZR2UU96x1pCHPCY8g8gvCY-c7wk',
    appId: '1:1066615778167:android:96acfdf9e4f57b76a18f72',
    messagingSenderId: '1066615778167',
    projectId: 'farm-to-home-8c520',
    storageBucket: 'farm-to-home-8c520.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlF1sGpJ9nvQ4e4FC1jBYnmYoJTvqASjM',
    appId: '1:1066615778167:ios:81630d482497e1d4a18f72',
    messagingSenderId: '1066615778167',
    projectId: 'farm-to-home-8c520',
    storageBucket: 'farm-to-home-8c520.firebasestorage.app',
    iosBundleId: 'com.example.farmToHomeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlF1sGpJ9nvQ4e4FC1jBYnmYoJTvqASjM',
    appId: '1:1066615778167:ios:81630d482497e1d4a18f72',
    messagingSenderId: '1066615778167',
    projectId: 'farm-to-home-8c520',
    storageBucket: 'farm-to-home-8c520.firebasestorage.app',
    iosBundleId: 'com.example.farmToHomeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-pJfFVndCqQENAsYHNjd9-kLVwz-wXsw',
    appId: '1:1066615778167:web:d9d5b42bf51693d7a18f72',
    messagingSenderId: '1066615778167',
    projectId: 'farm-to-home-8c520',
    authDomain: 'farm-to-home-8c520.firebaseapp.com',
    storageBucket: 'farm-to-home-8c520.firebasestorage.app',
    measurementId: 'G-993DVNWDG5',
  );
}
