-- PostgreSQL schema for product management module
CREATE TABLE IF NOT EXISTS products (
    id BIGSERIAL PRIMARY KEY,
    product_name VARCHAR(150) NOT NULL,
    slug VARCHAR(180) NOT NULL UNIQUE,
    category VARCHAR(40) NOT NULL,
    subcategory VARCHAR(120),
    telugu_name VARCHAR(150),
    description VARCHAR(1000) NOT NULL,
    image_alt_text VARCHAR(200),
    farmer_id BIGINT,
    market_price DOUBLE PRECISION,
    retail_price_min DOUBLE PRECISION,
    retail_price_max DOUBLE PRECISION,
    original_price DOUBLE PRECISION NOT NULL CHECK (original_price > 0),
    selling_price DOUBLE PRECISION NOT NULL CHECK (selling_price > 0),
    discount_percentage DOUBLE PRECISION NOT NULL DEFAULT 0 CHECK (discount_percentage >= 0),
    available_units VARCHAR(60),
    price DOUBLE PRECISION NOT NULL CHECK (price > 0),
    stock_quantity DOUBLE PRECISION NOT NULL DEFAULT 0 CHECK (stock_quantity >= 0),
    quantity DOUBLE PRECISION NOT NULL DEFAULT 0 CHECK (quantity >= 0),
    unit VARCHAR(20) NOT NULL,
    image_url VARCHAR(500),
    farmer_name VARCHAR(150) NOT NULL,
    farmer_location VARCHAR(200) NOT NULL,
    minimum_order_quantity DOUBLE PRECISION DEFAULT 0 CHECK (minimum_order_quantity >= 0),
    maximum_order_quantity DOUBLE PRECISION DEFAULT 0 CHECK (maximum_order_quantity >= 0),
    status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
    is_featured BOOLEAN NOT NULL DEFAULT FALSE,
    is_organic BOOLEAN NOT NULL DEFAULT FALSE,
    is_pre_order BOOLEAN NOT NULL DEFAULT FALSE,
    expected_delivery_date DATE,
    last_price_updated_at TIMESTAMP,
    price_source VARCHAR(120),
    stock_status VARCHAR(30) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);
